### ISSUE TITLE
Multiple compilation errors

### ISSUE THREAD

**Issue by SaraVeterini** [CCob/PwnyForm#2]
Since there are a lot of compilation errors during build, could you share the executable of the tool?

Thank you,
Sara

**Comment by CCob** [comment]
The compilation errors are probably from the missing Microsoft.Deployment.WindowsInstaller dependency.  You can get this from the Wix 3 deployment.

https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
